/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab_project;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;

/**
 *
 * @author amitmahmud26
 */
public class coffeeShop extends javax.swing.JFrame {

    public static double total = 0, tax = 0, subtotal = 0;
    public static void writeInfo(double total, double tax,double subtotal){
        try{
            File fp = new File("info.txt");
            PrintWriter pw = new PrintWriter(new FileWriter(fp, true));
            pw.println(total + " " + tax + " " + subtotal);
            pw.close();
        }
        catch(IOException e){}
    }

    /**
     * Creates new form coffeeShop
     */
    public coffeeShop() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        radTea = new javax.swing.JRadioButton();
        radCoffee = new javax.swing.JRadioButton();
        radCap = new javax.swing.JRadioButton();
        chkPlain = new javax.swing.JCheckBox();
        chkToast = new javax.swing.JCheckBox();
        chkSalt = new javax.swing.JCheckBox();
        btnClear = new javax.swing.JButton();
        btnEnter = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfTotal = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tfTax = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        tfSubtotal = new javax.swing.JTextPane();
        btnReceipt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Chalkduster", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(111, 78, 55));
        jLabel1.setText("Coffee Shop");

        radTea.setText("Tea                    20 /-");
        radTea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radTeaActionPerformed(evt);
            }
        });

        radCoffee.setText("Coffee                50 /-");
        radCoffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radCoffeeActionPerformed(evt);
            }
        });

        radCap.setText("Cappuccino      120 /-");
        radCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radCapActionPerformed(evt);
            }
        });

        chkPlain.setText("Plain Biscuits     10 /-");
        chkPlain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPlainActionPerformed(evt);
            }
        });

        chkToast.setText("Toast                 15 /-");

        chkSalt.setText("Saltest               15 /-");
        chkSalt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSaltActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnEnter.setText("Enter");
        btnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterActionPerformed(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        jLabel2.setText("Total");

        jLabel3.setText("Tax");

        jLabel4.setText("Subtotal");

        jScrollPane1.setViewportView(tfTotal);

        jScrollPane2.setViewportView(tfTax);

        jScrollPane3.setViewportView(tfSubtotal);

        btnReceipt.setText("Get Receipt");
        btnReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReceiptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(67, 67, 67)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(radCap)
                                                        .addComponent(radCoffee)
                                                        .addComponent(radTea)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(35, 35, 35)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(btnClear)
                                                                        .addComponent(btnEnter)
                                                                        .addComponent(btnExit))))
                                                .addGap(110, 110, 110)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(chkToast)
                                                        .addComponent(chkPlain)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel4))
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addComponent(chkSalt))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(116, 116, 116)
                                                .addComponent(jLabel1))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(231, 231, 231)
                                                .addComponent(btnReceipt)))
                                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel1)
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(radTea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(radCoffee)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(radCap))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(chkPlain)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(chkToast)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(chkSalt)))
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel4)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnClear)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnEnter)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnExit)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                .addComponent(btnReceipt)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void radCoffeeActionPerformed(java.awt.event.ActionEvent evt) {
        // if coffee is selected
        if(radCoffee.isSelected()){
            radCap.setSelected(false);
            radTea.setSelected(false);
        }
    }

    private void radCapActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if(radCap.isSelected()){
            radCoffee.setSelected(false);
            radTea.setSelected(false);
        }
    }

    private void chkPlainActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void radTeaActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if(radTea.isSelected()){
            radCap.setSelected(false);
            radCoffee.setSelected(false);
        }
    }

    private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        // double subtotal, total = 0, tax;
        final double taxRate = 0.15;
        if(radTea.isSelected()){
            total = total + 20;
        }
        else if(radCoffee.isSelected()){
            total = total + 50;
        }
        else if(radCap.isSelected()){
            total = total + 120;
        }

        if(chkPlain.isSelected()){
            total = total + 10;
        }
        if(chkToast.isSelected()){
            total = total + 15;
        }
        if(chkSalt.isSelected()){
            total = total + 15;
        }

        tfTotal.setText(Double.toString(total));
        total = Double.parseDouble(tfTotal.getText());
        tax = total * taxRate;
        subtotal = total + tax;
        tfTax.setText(Double.toString(tax));
        tfSubtotal.setText(Double.toString(subtotal));

        writeInfo(total,tax,subtotal);

//try {
//
//        File fp = new File("info.txt");
//        PrintWriter pw = new PrintWriter(new FileWriter(fp, true));
//        pw.println(total + " " + tax + " " + subtotal);
//        pw.close();
//    }
//catch (IOException e) {
//      System.out.println("An error occurred.");
//      e.printStackTrace();
//    }
    }

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        System.exit(0);
    }

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        radTea.setSelected(false);
        radCoffee.setSelected(false);
        radCap.setSelected(false);

        chkPlain.setSelected(false);
        chkToast.setSelected(false);
        chkSalt.setSelected(false);

        tfTotal.setText("");
        tfTax .setText("");
        tfSubtotal.setText("");



    }

    private void btnReceiptActionPerformed(java.awt.event.ActionEvent evt) {
        receipt r = new receipt();
        dispose();
    }

    private void chkSaltActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(coffeeShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new coffeeShop().setVisible(true);
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnEnter;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnReceipt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chkPlain;
    private javax.swing.JCheckBox chkSalt;
    private javax.swing.JCheckBox chkToast;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton radCap;
    private javax.swing.JRadioButton radCoffee;
    private javax.swing.JRadioButton radTea;
    private javax.swing.JTextPane tfSubtotal;
    private javax.swing.JTextPane tfTax;
    private javax.swing.JTextPane tfTotal;
    // End of variables declaration                   

}

